### ISSUE TITLE
Can you please add a question to the solved programs?

### ISSUE THREAD

**Issue by vishnucool220** [DollarAkshay/C-and-CPP-Programs#1]
Hi,
I have seen your programs they are quite good. But I would like to request for a comment or question on the top of each program on " What is it about "? Because most of the programms i don't understand what is the main goal of that particular program.Thanks

**Comment by DollarAkshay** [comment]
I usually provide a link to that program. If you put that link in your browser it will show you the problem statement

**Comment by vishnucool220** [comment]
i am so sorry but  i did't find links to any of the questions. for eg : https://github.com/DollarAkshay/C-and-CPP-Programs/blob/master/Code%20Golf/Binary_Search_Golf.c ? May i know what this code does ?Thanks

**Comment by DollarAkshay** [comment]
That atcually is something I did on my own. Its just code golf for binary search :)
